name: Dependabot PR actions
on: pull_request_target

jobs:
  dependabot:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Check out code
        uses: actions/checkout@v6
        with:
          token: ${{ steps.github_app_token.outputs.token }}
          ref: ${{ github.head_ref }}

      - name: Add skip-changelog label
        run: gh pr edit "${{ github.event.pull_request.html_url }}" --add-label "skip-changelog"
        env:
          GITHUB_TOKEN: ${{ steps.github_app_token.outputs.token }}
