name: Unit Tests

on: [ push, pull_request ]

env:
  YARN_IGNORE_ENGINES: true

jobs:
  unit-tests:
    name: Run unit tests
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest , windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Enable longer filenames
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true

      - name: Checkout Branch
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - id: install-dashboards
        uses: opensearch-project/opensearch-build/.github/actions/setup-opensearch-dashboards@643b632712710159088d5f0798de7e91c1f2b8f7
        with:
           plugin_name: security-dashboards-plugin

      - name: Run lint
        run: yarn lint
        working-directory: ${{ steps.install-dashboards.outputs.plugin-directory }}

      - name: Run unit test
        run: yarn test:jest_ui --coverage
        working-directory: ${{ steps.install-dashboards.outputs.plugin-directory }}

      - name: Uploads coverage
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
