name: Unit Tests

on: [ push, pull_request ]

jobs:
  unit-tests:
    name: Run unit tests
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest , windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Enable longer filenames
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true

      - name: Checkout Branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - id: install-dashboards
        uses: opensearch-project/opensearch-build/.github/actions/setup-opensearch-dashboards@3fe95a610492df770c414c135ae2abd31b9c219d
        with:
           plugin_name: security-dashboards-plugin

      - name: Run lint
        run: yarn lint
        working-directory: ${{ steps.install-dashboards.outputs.plugin-directory }}

      - name: Run unit test
        run: yarn test:jest_ui --coverage
        working-directory: ${{ steps.install-dashboards.outputs.plugin-directory }}

      - name: Uploads coverage
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
